CREATE TABLE products
(id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
price NUMERIC(7,2) NOT NULL,
date_created DATE NOT NULL,
user_id INTEGER NOT NULL REFERENCES user(id),
agency_id INTEGER NOT NULL REFERENCES agencies(id),
roadmap_id INTEGER NOT NULL REFERENCES roadmaps(id)
)